# Generated by Django 4.2.16 on 2024-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_customuser_payment_usertask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='description',
            new_name='task_description',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence. Um usuário receberá todas as permissões concedidas a cada um de seus grupos.', related_name='customuser_set', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='customuser_set', to='auth.permission', verbose_name='permissões de usuário'),
        ),
    ]
